version: "3.7"
services:
  mysql:
    image: 'mysql-server:8.0'
    container_name: mysql
    env_file: 
      - mysql.env
    ports:
      - 3306:3306
    volumes: 
      - mysql:/var/lib/mysql/data/
  zabbix-server:
    image: 'zabbix/zabbix-server-mysql:latest'
    container_name: zabbix-server
    env_file: 
      - zabbix-server.env
    ports: 
      - 10051:10051
    depends_on: 
      - mysql
  zabbix-frontend:
    image: 'zabbix/zabbix-web-nginx-mysql:latest'
    container_name: zabbix-frontend
    env_file: 
      - zabbix-frontend.env
    ports:
      - 8090:8080
    depends_on:
      - zabbix-server
      - mysql
  zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    privileged: true   #access mode for allowing resource access
    environment:
      - ZBX_SERVER_HOST=zabbix-server #the IP/Dns of Zabbix server
    volumes:
      -zabbix-agent:/etc/zabbix/

volumes: 
  postgres:
  zabbix-agent:
  zabbix-server: